# Generated by Django 5.0.4 on 2024-07-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
